import{i as a,S as m}from"./assets/vendor-7659544d.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const h="35544467-972bad3ac294320c3ee48db53",f="https://pixabay.com/api/";async function p(r,o){const t=`${f}?key=${h}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const e=await axios.get(t);if(e.status!==200)throw new Error("Failed to fetch images");return e.data.hits}catch(e){throw console.error("Error fetching images:",e.message),e}}function y(){a.show({title:"Loading",message:"Fetching images from Pixabay...",theme:"dark",progressBarColor:"#17a2b8",position:"bottomRight"})}function u(){a.hide({},document.querySelector(".iziToast"))}function w(r){const o=document.querySelector(".gallery");if(o.innerHTML="",r.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}const n=document.createDocumentFragment();r.forEach(t=>{const e=document.createElement("div");e.classList.add("card"),e.innerHTML=`
            <img src="${t.webformatURL}" alt="${t.tags}" data-large="${t.largeImageURL}">
            <div class="info">
                <span>${t.likes} Likes</span>
                <span>${t.views} Views</span>
                <span>${t.comments} Comments</span>
                <span>${t.downloads} Downloads</span>
            </div>
        `,n.appendChild(e)}),o.appendChild(n)}let l="",i=1;const L=document.querySelector("#search-form"),d=document.querySelector("#load-more");document.querySelector("#loading-indicator");L.addEventListener("submit",async r=>{r.preventDefault(),l=document.querySelector("#search-input").value.trim(),i=1,await g(l,i)});d.addEventListener("click",async()=>{i++,await g(l,i)});async function g(r,o){y();try{const n=await p(r,o);if(w(n),n.length===0){u(),a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}o===1&&new m(".gallery img").refresh(),n.length<15?(d.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})):d.style.display="block",b()}catch(n){console.error("Error searching for images:",n.message)}finally{u()}}function b(){const r=document.querySelector(".gallery").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
